FEATURE: Exchangeable proxy aware storages and targets
sitegeist/Sitegeist.MagicWand pull request #42
Opened 2020-09-26 13:49 UTC by daniellienert

In a project we use a local S3 storage instead of the file system storage in order to be get the dev environment as similar as possible to the live environment. 

In order to use the resource proxy feature of magicwand I had to build a `MagicWandProxyAwareS3Storage` as well as a simple `ProxyAwareFileSystemTarget` (included). To make that possible, the code now checks for `ProxyAwareTargetInterface` and `ProxyAwareStorageInterface` instead of the provided implementations.

Also fixed some smaller bugs and did some boy-scout refactorings.

2020-10-12 08:33 UTC, grebaldi requested changes
Thanks for the PR @daniellienert!

Code-wise this looks fine and I could verify that it works as expected in a Neos 5.1 setup.

My only concern is with the adjusted ActionRequest creation in https://github.com/sitegeist/Sitegeist.MagicWand/pull/42/commits/429c915ca91fda6e2e865b30246f2b73e83433c1.

This method has been added to Flow in this commit: https://github.com/neos/flow-development-collection/commit/e2eb5a37107c2d84f32334f1bd72dd2c49bbde80

That would require us to raise our version constraint for Flow and do a major release. 

I'd be fine with that, but I'd like to ask you to add the adjusted version constraint to this PR.

2020-10-12 08:33 UTC, grebaldi commented on Classes/ResourceManagement/ProxyAwareTargetTrait.php
> +            $request = ActionRequest::fromHttpRequest($requestHandler->getComponentContext()->getHttpRequest());
I don't think this is compatible with our version constraint for Flow:
```
"neos/flow": "~4.0 || ~5.0 || ~6.0 || dev-master"
```

2020-10-12 10:38 UTC, daniellienert commented
Hey @grebaldi,
thanks for the review. I adjusted the minimal FLow version.

2020-10-12 10:40 UTC, grebaldi approved these changes

2020-10-12 10:42 UTC, grebaldi commented
Thanks a lot @daniellienert :)

Are you fine with merging this one, @mficzel?

2020-10-12 11:04 UTC, mficzel approved these changes
I would like to see some lines in the readme but other than that i like and would also be fine with merging as is.

2020-10-21 18:25 UTC, daniellienert commented
@mficzel / @grebaldi: done

2020-10-28 12:47 UTC, merged